version: '3.7'

services:
  course-service:
    image: stevenpadilla/course_service:1.3.0
    build:
      context: .
      dockerfile: Dockerfile
      target: imageCourse
    container_name: course-service
    env_file:
      - .env
    expose:
      - '1709'
    ports:
      - '3001:1709'
    command: node dist/src/index.js